#!/usr/bin/env python
"""Move a clone's local, git-ignored artefacts from the old generation directories into generations/.

Commit 155dc6c moved ten generation directories from the repository root into
``generations/``.  Pulling that commit moves every tracked file, but git leaves ignored
files where they were: fitted models, prediction dumps and bench caches stay under
``<root>/<name>/``, where nothing reads them any more.  The legacy block in ``.gitignore``
keeps them ignored until they are moved.  This script moves them.

For each generation name whose old directory ``<root>/<name>/`` still exists, every file in
it is classified with git:

* tracked by git: unexpected after the move, so it is reported and skipped;
* untracked and not ignored (your own work): reported and skipped, unless
  ``--include-untracked`` is given, in which case it is treated like an ignored file;
* ignored (``git check-ignore``): its destination is ``generations/<name>/<same relative
  path>``.  If the destination already holds identical bytes, the old copy is deleted.  If
  the destination holds something else, that is a conflict: both are left untouched.
  Otherwise the file is moved.

Files under ``__pycache__``, ``.pytest_cache``, ``.ruff_cache`` or ``.mypy_cache``, and
``.DS_Store`` files, are regenerated by the tools that write them.  They are deleted instead
of moved, so stale bytecode never lands in generations/ and never counts as a conflict.

Nothing changes without ``--apply``.  With ``--apply``, directories left empty under the old
generation directories are removed afterwards.  The exit status is 1 when there was at least
one conflict (in a dry run too), 2 when the repository cannot be inspected, and 0 otherwise.

Usage (from the repository root)::

    .venv/bin/python generations/migrate_local_artifacts.py                 # dry run
    .venv/bin/python generations/migrate_local_artifacts.py --apply
    .venv/bin/python generations/migrate_local_artifacts.py --apply --include-untracked

Standard library and the git command line only.
"""
from __future__ import annotations

import argparse
import filecmp
import os
import shutil
import subprocess
import sys
from pathlib import Path

GENERATIONS = (
    "gen12_eu_pred",
    "gen12_2_eu_pred",
    "gen12_eu_pred_2",
    "gen13_separation",
    "gen14_direction",
    "gen15_curve",
    "gen16_anchor",
    "gen16_leads",
    "gen16_protocol",
    "gen17_pairdiff",
)
REGENERATED_DIRS = {"__pycache__", ".pytest_cache", ".ruff_cache", ".mypy_cache"}
REGENERATED_FILES = {".DS_Store"}

ROOT = Path(__file__).resolve().parents[1]


class GitError(RuntimeError):
    pass


def _git(root: Path, args: list, stdin: bytes | None = None, ok_codes=(0,)) -> bytes:
    try:
        result = subprocess.run(["git", *args], cwd=root, input=stdin, capture_output=True, check=False)
    except OSError as error:
        raise GitError(f"cannot run git: {error}") from error
    if result.returncode not in ok_codes:
        message = result.stderr.decode("utf-8", "replace").strip()
        raise GitError(f"git {' '.join(args)} failed ({result.returncode}): {message}")
    return result.stdout


def _split_z(data: bytes) -> list:
    return [item.decode("utf-8", "surrogateescape") for item in data.split(b"\0") if item]


def _files_under(directory: Path) -> list:
    """Every file (or symlink) under ``directory``, without following symlinks."""
    found = []
    for dirpath, dirnames, filenames in os.walk(directory):
        base = Path(dirpath)
        for name in dirnames:
            if (base / name).is_symlink():
                found.append(base / name)
        found.extend(base / name for name in filenames)
    return sorted(found)


def _regenerated(relative: str) -> bool:
    parts = relative.split("/")
    return parts[-1] in REGENERATED_FILES or any(part in REGENERATED_DIRS for part in parts[:-1])


def _same(source: Path, destination: Path) -> bool:
    if source.is_symlink() or destination.is_symlink():
        return (source.is_symlink() and destination.is_symlink()
                and os.readlink(source) == os.readlink(destination))
    return destination.is_file() and filecmp.cmp(source, destination, shallow=False)


def _blocked(destination: Path, stop: Path) -> str | None:
    """Why ``destination`` cannot receive a file, or None if it is free."""
    if os.path.lexists(destination):
        return None if destination.is_file() or destination.is_symlink() else "a directory is in the way"
    parent = destination.parent
    while parent != stop and parent != parent.parent:
        if os.path.lexists(parent) and not parent.is_dir():
            return f"{parent.as_posix()} is a file, not a directory"
        parent = parent.parent
    return None


def migrate(root: Path, apply: bool, include_untracked: bool) -> int:
    toplevel = Path(_git(root, ["rev-parse", "--show-toplevel"]).decode("utf-8").strip()).resolve()
    if toplevel != root.resolve():
        raise GitError(f"{root} is not the top level of its git repository ({toplevel})")
    if not (root / "generations").is_dir():
        raise GitError(f"{root / 'generations'} does not exist")

    verb = "" if apply else "would "
    print(f"{'APPLY' if apply else 'DRY RUN (pass --apply to act)'}: repository root {root}")
    counts = dict(moved=0, duplicate=0, regenerated=0, conflict=0, tracked=0, untracked=0, dirs=0)

    for name in GENERATIONS:
        old = root / name
        if old.is_symlink() or not old.is_dir():
            if old.is_symlink():
                print(f"\n{name}/ is a symlink, not a directory: skipped")
            continue
        print(f"\n{name}/")
        tracked = set(_split_z(_git(root, ["ls-files", "-z", "--", f"{name}/"])))
        files = [(path, path.relative_to(root).as_posix()) for path in _files_under(old)]
        untracked = [rel for _, rel in files if rel not in tracked]
        ignored = set()
        if untracked:
            stdin = b"\0".join(rel.encode("utf-8", "surrogateescape") for rel in untracked) + b"\0"
            ignored = set(_split_z(_git(root, ["check-ignore", "-z", "--stdin"], stdin=stdin, ok_codes=(0, 1))))

        for source, rel in files:
            if rel in tracked:
                counts["tracked"] += 1
                print(f"  TRACKED    {rel}: tracked by git at its old path (unexpected), skipped")
                continue
            if rel not in ignored and not include_untracked:
                counts["untracked"] += 1
                print(f"  UNTRACKED  {rel}: not ignored, so possibly your own work; skipped "
                      f"(--include-untracked moves it)")
                continue
            if _regenerated(rel):
                counts["regenerated"] += 1
                print(f"  REGEN      {rel}: regenerated tool cache, {verb}delete")
                if apply:
                    source.unlink()
                continue
            destination = root / "generations" / rel
            target = destination.relative_to(root).as_posix()
            reason = _blocked(destination, root / "generations")
            if reason is None and os.path.lexists(destination) and not _same(source, destination):
                reason = f"{target} exists with different content"
            if reason is not None:
                counts["conflict"] += 1
                print(f"  CONFLICT   {rel}: {reason}; both left untouched")
                continue
            if os.path.lexists(destination):
                counts["duplicate"] += 1
                print(f"  DUPLICATE  {rel}: identical to {target}, {verb}delete the old copy")
                if apply:
                    source.unlink()
                continue
            counts["moved"] += 1
            print(f"  MOVE       {rel} -> {target}")
            if apply:
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(source), str(destination))

        if apply:
            for dirpath, _, _ in sorted(os.walk(old), key=lambda item: -len(Path(item[0]).parts)):
                directory = Path(dirpath)
                if not directory.is_symlink() and directory.is_dir() and not any(directory.iterdir()):
                    directory.rmdir()
                    counts["dirs"] += 1
                    print(f"  RMDIR      {directory.relative_to(root).as_posix()}/")

    rows = [(f"{verb}move", counts["moved"]),
            (f"{verb}delete (identical copy)", counts["duplicate"]),
            (f"{verb}delete (regenerated)", counts["regenerated"]),
            ("conflicts (left untouched)", counts["conflict"]),
            ("tracked, skipped", counts["tracked"]),
            ("untracked, skipped", counts["untracked"])]
    if apply:
        rows.append(("empty directories removed", counts["dirs"]))
    print("\nSummary")
    for label, count in rows:
        print(f"  {label + ':':<34}{count}")
    if counts["conflict"]:
        print("Resolve each conflict by hand (keep one copy, delete the other), then run again.")
    return 1 if counts["conflict"] else 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Move ignored artefacts left at the old generation paths into generations/.")
    parser.add_argument("--apply", action="store_true", help="act; without it nothing changes")
    parser.add_argument("--include-untracked", action="store_true",
                        help="also move untracked files that git does not ignore")
    args = parser.parse_args(argv)
    try:
        return migrate(ROOT, apply=args.apply, include_untracked=args.include_untracked)
    except GitError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
