"""Assemble runs/gen8_architecture/uncertainty/uncertainty.md from the CSVs.

Also audits the uncertainty policies already in
runs/gen8_architecture/active_acquisition/primary_detail.parquet, because two of
them turn out not to have been uncertainty policies at all.

Every number in the markdown is read back out of a CSV in the same directory --
nothing is transcribed by hand.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from lanthanide_separation.gen8.inference import paired_chemotype_bootstrap  # noqa: E402
from lanthanide_separation.gen8.report import md_table  # noqa: E402

OUT = ROOT / "runs" / "gen8_architecture" / "uncertainty"
BOOT_SEED = 8675309


def audit_prior_policies() -> pd.DataFrame:
    """Re-score the k=1 uncertainty arms already on disk, and check their sources."""
    oof = pd.read_parquet(ROOT / "runs/gen7_architecture/finalists/oof_predictions.parquet")
    availability = oof.groupby("model").agg(
        rows_total=("model", "size"),
        rows_with_prediction_sd=("extra__prediction_sd", lambda s: int(s.notna().sum())),
    ).reset_index()
    availability.to_csv(OUT / "audit_prediction_sd_availability.csv", index=False)

    src = ROOT / "runs/gen8_architecture/active_acquisition/primary_detail.parquet"
    # This file is regenerated by the acquisition sweep and moved under this
    # session's feet once already, so the snapshot actually read is pinned here.
    import hashlib
    import datetime as _dt
    digest = hashlib.sha256(src.read_bytes()).hexdigest()
    detail = pd.read_parquet(src)
    pd.DataFrame([{
        "file": str(src.relative_to(ROOT)),
        "mtime_utc": _dt.datetime.fromtimestamp(src.stat().st_mtime, _dt.timezone.utc).isoformat(),
        "bytes": src.stat().st_size, "rows": len(detail),
        "sha256": digest,
    }]).to_csv(OUT / "audit_source_provenance.csv", index=False)
    arms = ["RANDOM", "MAX_ENSEMBLE_SD", "MIN_ENSEMBLE_SD", "MAX_MODEL_DISAGREEMENT",
            "MAX_PREDICTIVE_VARIANCE", "CENTRAL", "MEDOID", "ORACLE[OFFSET_K1]"]
    sub = detail[(detail["k"] == 1) & (detail["adapter"] == "OFFSET_K1")
                 & (detail["policy"].isin(arms))].rename(columns={"policy": "arm"})
    comparisons = {
        "RANDOM - MAX_ENSEMBLE_SD": ("RANDOM", "MAX_ENSEMBLE_SD"),
        "RANDOM - MIN_ENSEMBLE_SD": ("RANDOM", "MIN_ENSEMBLE_SD"),
        "MAX_ENSEMBLE_SD - MIN_ENSEMBLE_SD": ("MAX_ENSEMBLE_SD", "MIN_ENSEMBLE_SD"),
        "RANDOM - MAX_MODEL_DISAGREEMENT": ("RANDOM", "MAX_MODEL_DISAGREEMENT"),
        "RANDOM - MAX_PREDICTIVE_VARIANCE": ("RANDOM", "MAX_PREDICTIVE_VARIANCE"),
        "RANDOM - CENTRAL": ("RANDOM", "CENTRAL"),
    }
    boot = paired_chemotype_bootstrap(sub, comparisons, seed=BOOT_SEED)
    boot.to_csv(OUT / "audit_prior_policies.csv", index=False)
    means = (sub.groupby(["arm", "extractant"])["mae"].mean()
             .groupby("arm").mean().rename("macro_mae").reset_index())
    means.to_csv(OUT / "audit_prior_macro.csv", index=False)
    return availability


def read(name: str) -> pd.DataFrame:
    return pd.read_csv(OUT / name)


def main() -> None:
    availability = audit_prior_policies()
    within = read("calibration_within_ligand.csv").set_index("source")
    across = read("calibration_across_ligand.csv").set_index("source")
    selfc = read("calibration_self_consistency.csv")
    pooled = read("calibration_curve_pooled.csv")
    wcurve = read("calibration_curve_within_ligand.csv")
    dspear = read("decision_spearman.csv").set_index("source")
    policies = read("decision_policies.csv").set_index("arm")
    dboot = read("decision_bootstrap_vs_random.csv").set_index("comparison")
    mech = read("mechanism_spearman.csv")
    lvl = read("level_vs_shape.csv").iloc[0]
    cen = read("centrality_explains_leaderboard.csv").iloc[0]
    ceq = read("mechanism_oracle_equivalence.csv").iloc[0]
    common = read("calibration_within_ligand_common.csv").set_index("source")
    axes_used = read("gp_axes_used.csv")
    axes_counts = axes_used["n_axes"].value_counts()
    triage_s = read("triage_spearman.csv").set_index("source")
    triage_c = read("triage_budget_curve.csv")
    triage_b = read("triage_bootstrap.csv")
    audit = read("audit_prior_policies.csv")
    prior = read("audit_prior_macro.csv").set_index("arm")
    prov = read("audit_source_provenance.csv").iloc[0]
    prov_mtime = str(prov["mtime_utc"])
    prov_rows = int(prov["rows"])
    prov_sha = str(prov["sha256"])[:12]

    calib = within.reset_index()[
        ["source", "within_ligand_rho", "ci_low", "ci_high",
         "frac_cells_positive", "n_ligand_seed_cells"]].merge(
        across.reset_index()[["source", "across_ligand_rho_mean", "seeds_positive"]],
        on="source")
    calib.columns = ["source", "within-ligand rho", "ci_lo", "ci_hi",
                     "frac cells rho>0", "n cells", "across-ligand rho", "seeds>0"]

    tree_curve = pooled[pooled["source"] == "u_tree_sd"][
        ["decile", "mean_u", "realised_mae", "n"]]
    wpivot = wcurve.pivot(index="quintile", columns="source",
                          values="centred_mae").reset_index()
    wcols = ["quintile", "u_tree_sd", "u_model_spread", "u_cond_nn1", "u_cond_nn5",
             "u_gp_var_design", "u_gp_var_train"]

    dec = dspear.reset_index()[
        ["source", "rho_vs_one_shot_mae", "rho_vs_one_shot_mae_lo",
         "rho_vs_one_shot_mae_hi", "rho_vs_median_dev", "rho_vs_abs_resid"]]
    dec.columns = ["source", "rho(u, 1-shot MAE)", "ci_lo", "ci_hi",
                   "rho(u, dev from median r)", "rho(u, abs r)"]

    pol = policies.reset_index()[
        ["arm", "macro_mae", "macro_centrality", "seed_104729", "seed_130363",
         "seed_155921", "seed_196613", "seed_262147"]]
    pol.columns = ["arm", "macro MAE", "extremity of pick", "s1", "s2", "s3", "s4", "s5"]

    db = dboot.reset_index()[
        ["comparison", "point", "ci95_low", "ci95_high", "bca_low", "bca_high",
         "units_improved", "seeds_positive"]]
    db.columns = ["RANDOM minus arm (positive = arm better)", "delta", "ci_lo", "ci_hi",
                  "bca_lo", "bca_hi", "ligands better /143", "seeds /5"]

    av = availability[availability["rows_with_prediction_sd"] > 0][
        ["model", "rows_with_prediction_sd", "rows_total"]]
    aud = audit[["comparison", "point", "ci95_low", "ci95_high", "seeds_positive"]]
    aud.columns = ["comparison (positive = right-hand arm better)", "delta",
                   "ci_lo", "ci_hi", "seeds /5"]
    prior_tab = prior.reset_index()[["arm", "macro_mae"]].sort_values("macro_mae")

    tri = triage_c.pivot(index="budget_M", columns="selector",
                         values="macro_mae").reset_index()
    tri_cols = ["budget_M", "RANDOM", "u_tree_sd", "u_model_spread", "u_lig_mech",
                "u_gp_var_design", "ORACLE_gain"]
    tb = triage_b[triage_b["budget_M"] == 29][
        ["comparison", "point", "ci95_low", "ci95_high", "block_macro", "seeds_positive"]]
    tb.columns = ["RANDOM_budget minus selector", "delta", "ci_lo", "ci_hi",
                  "chemotype macro", "seeds /5"]
    tri_s = triage_s.reset_index()[
        ["source", "rho_vs_zero_shot_mae", "rho_vs_gain_from_one_shot",
         "seeds_positive_gain"]]
    tri_s.columns = ["source", "rho(u, zero-shot MAE)", "rho(u, gain from measuring)",
                     "seeds>0 /5"]

    lvl_tab = pd.DataFrame([
        {"quantity": "abs(median residual) -- the level error",
         "macro over 143 ligands": float(lvl["macro_abs_median_residual (level error)"])},
        {"quantity": "mean abs(r - median r) -- the shape error, = oracle level",
         "macro over 143 ligands": float(lvl["macro_mad_residual (shape error, = oracle level)"])},
        {"quantity": "zero-shot MAE",
         "macro over 143 ligands": float(lvl["macro_zero_shot"])},
    ])

    def m(arm: str, col: str = "macro_mae") -> float:
        return float(policies.loc[arm, col])

    def b(label: str) -> pd.Series:
        return dboot.loc[label]

    rand = m("RANDOM(expected)")
    orc = m("ORACLE_1SHOT")
    minabs = m("ORACLE_MIN_ABS_RESID")
    gpmin = m("MIN[u_gp_var_design]")
    maxtree = m("MAX[u_tree_sd]")
    zshot = m("ZERO_SHOT")
    b_gp = b("RANDOM - MIN[u_gp_var_design]")
    b_tree = b("RANDOM - MAX[u_tree_sd]")
    b_abs = b("RANDOM - ORACLE_MIN_ABS_RESID")
    tsd_across = float(across.loc["u_tree_sd", "across_ligand_rho_mean"])
    spread29 = triage_b[(triage_b["budget_M"] == 29)
                        & (triage_b["comparison"].str.endswith("u_model_spread"))].iloc[0]
    tri29 = triage_c[triage_c["budget_M"] == 29].set_index("selector")["macro_mae"]

    parts: list[str] = []

    parts.append(f"""# 20. Is uncertainty useful?

**Short answer: the uncertainties are real, and they are useless for the
decision that matters.**

Every uncertainty source available for the frozen global model
(`REC_ecfp_plus_recovered`) was built and then scored twice: once as a
*calibration* signal (does it rank the error?) and once as a *decision* signal
(does it rank the candidate rows you could go and measure?).  The two answers
point in opposite directions.  The tree-ensemble sd ranks unseen extractants by
difficulty at across-ligand Spearman {tsd_across:.3f}, with a cleanly monotone
calibration curve -- and measuring its most uncertain row costs {maxtree - rand:+.3f} log
units against a random row ({maxtree:.3f} vs {rand:.3f}).

The reason is not that the uncertainties are bad.  It is that under offset
calibration the quantity a 1-shot policy must minimise is
**abs(r_i - median(r))**, an unsigned *deviation from the ligand's own median
residual*.  Ranking candidates by that quantity reproduces the exhaustive 1-shot
oracle **exactly** -- in all {int(ceq['n_cells'])} (seed, ligand) cells, to
{float(ceq['max_abs_gap_vs_exhaustive_oracle']):.1e}.  Ranking them
by abs(r_i), which is what a perfectly calibrated uncertainty gives you, is
{-float(b_abs['point']):.3f} log units *worse than random*.  Uncertainty measures
extremity; the policy needs typicality.

---

## 20.1 What was measured

Frozen model, 5 split seeds x 5 folds, held-out chemotypes.  Two populations,
because the two questions have different supports.  **Calibration (20.2)** scores
every held-out row of every held-out extractant: {int(len(axes_used))} (seed, ligand)
cells over {int(axes_used['extractant'].nunique())} extractants, 26,240 row-seeds.
**Everything with a decision in it (20.3-20.5)** needs at least two candidate rows
per cell so that a 1-shot MAE exists, which leaves 143 unseen extractants in 72
Tanimoto chemotypes, {int(ceq['n_cells'])} cells and 26,105 candidate rows -- the
population every macro MAE and every interval below is computed on.  Residual
`r = log_D - prediction`.  The exact 1-shot MAE of every candidate row comes
from `cross_series/one_shot_candidate_scores.parquet`, whose definition was
re-derived from the OOF residuals before use and matches to machine precision:

    one_shot_mae(i) = mean over j != i of abs(r_j - r_i)
    zero_shot_mae   = mean over j of abs(r_j)
    oracle_level_mae= mean over j of abs(r_j - median(r))

so "which candidate should I measure" is answered in closed form rather than by
simulation, and no policy needs a repeat count.

Sources.  All are computable at prediction time; none sees a held-out label.

| id | source | level |
|---|---|---|
| `u_tree_sd` | tree-ensemble prediction sd of `TREE_MC_ecfp_massaction` | row |
| `u_tree_sd_mean` | mean tree-ensemble sd of the three `TREE_MC_*` arms | row |
| `u_model_spread` | sd of the 5 finalists' predictions at the same (row, seed) | row |
| `u_cond_nn1`, `u_cond_nn5` | k-th NN Euclidean distance to the fold's training rows in standardised condition space (log concentrations, temperature, contact time, metal Z, acid / diluent / additive one-hots; z-scored on the training fold) | row |
| `u_gp_var_design` | leave-one-out RBF-GP predictive variance over the ligand's own 1-3 varying condition axes, median-heuristic lengthscale | row |
| `u_gp_var_train` | RBF-GP predictive variance at the row given a 1200-row sample of the fold's training design | row |
| `u_lig_tanimoto` | `1 - nn_train_tanimoto` | ligand |
| `u_lig_mech` | mechanistic distance (36 descriptors from `gen8.mechanism`) to the nearest training ligand, standardised on the fold's training ligands | ligand |

A GP's predictive variance depends only on its inputs, so `u_gp_var_design` uses
no targets at all: it measures how tightly the rest of a ligand's own design
surrounds each candidate point.  Of the {int(len(axes_used))} (seed, ligand) cells,
{int(axes_counts.get(1, 0))} vary along one axis, {int(axes_counts.get(2, 0))} along two and
{int(axes_counts.get(3, 0))} along three (`gp_axes_used.csv`); the commonest axes
are metal Z and acid concentration.

The frozen model does **not** emit a per-row dispersion -- its
`extra__prediction_sd` column is 100% null.  Only these models carry one:

{md_table(av)}

so the tree-variance signal is taken from the frozen model's nearest
architectural sibling, `TREE_MC_ecfp_massaction`.  Section 20.6 shows that this
substitution is not what drives the result.

### An audit finding, first

Two of the three uncertainty policies already on disk were not uncertainty
policies.  `MAX_ENSEMBLE_SD` and `MIN_ENSEMBLE_SD` read `extra__prediction_sd`
(`scripts/gen8_kshot.py:65`), which is all-null for the frozen model, and
`gen8/kshot.py::_argmax_finite` falls back to `rng.choice` when no score is
finite -- as does `policy_min_sd`.  Both arms therefore drew **uniformly at
random**.  This is not an inference from the aggregates: loading the frozen
model's blocks through `scripts/gen8_kshot.py::load_blocks` gives
`uncertainty` with 0 finite values out of 26,240, and calling
`policy_max_sd`, `policy_min_sd` and `policy_random` on the same block with the
same generator state returns the **same index** every time
(`MAX_ENSEMBLE_SD` = `MIN_ENSEMBLE_SD` = `RANDOM` as functions, not merely in
mean).  `disagreement` is finite on all 26,240 rows, so
`MAX_MODEL_DISAGREEMENT` is a real policy.  The aggregates agree: the two sd
arms are indistinguishable from each other and from `RANDOM`.

{md_table(aud)}

{md_table(prior_tab)}

`MAX_PREDICTIVE_VARIANCE` is degenerate at k=1 for a different reason: with no
point yet selected, `_gp_posterior_variance` returns a constant vector, so
`argmax` always returns pool element 0, and `make_p2_split` sorts the pool, so
the arm measures the lowest-indexed candidate of the ligand -- an ordering
artefact, not a variance.  Verified by direct call: it returns `pool[0]` under
every generator state.  Only `MAX_MODEL_DISAGREEMENT` was a real uncertainty
policy, and it was already worse than random.

**Read the `seeds /5` column of that table with care.**  In this harness the
pool/evaluation split is seeded on `(harness seed, repeat, ligand)` and each
policy's generator on `(harness seed, repeat, policy name)` -- neither includes
the split seed -- and each ligand's rows appear in the same order in all five
seeds (checked).  Every policy therefore measures the *same physical rows* in all
five split seeds, so `5/5` there means five refits of the model agreeing over one
fixed set of draws, not five independent draws.  It applies to the arms in this
audit table only; sections 20.3-20.5 do not use that file.

**Caveat on the source.**  `primary_detail.parquet` is regenerated by the
acquisition sweep and was rewritten under this session at least once, and reads
taken at different times during the session returned different aggregates.  Which
bytes each earlier read saw was not recorded, so the difference is attributed to
the rewrite and not to anything else; an earlier draft of this section called one
of the reads torn, which the evidence does not support.  The snapshot this
section is computed from is pinned in
`audit_source_provenance.csv` ({prov_mtime} UTC, {prov_rows:,} rows, sha256
{prov_sha}), and every audit number above comes from a single read of it.  In
that snapshot RANDOM scores {float(prior.loc['RANDOM', 'macro_mae']):.4f}, MAX_ENSEMBLE_SD {float(prior.loc['MAX_ENSEMBLE_SD', 'macro_mae']):.4f} and MIN_ENSEMBLE_SD
{float(prior.loc['MIN_ENSEMBLE_SD', 'macro_mae']):.4f}; earlier snapshots gave 0.702 / 0.709 / 0.708 and 0.711 / 0.712 /
0.713.  The pinned snapshot is also the file on disk now, and ligand-macro,
row-pooled and seed-then-ligand aggregation of it all return the same numbers, so
the earlier values came from earlier *content*, not from a different reduction of
the same content.  The absolute level moves; the **MAX = MIN = RANDOM equality
holds in every snapshot observed**, and it holds by construction in the code,
which is the only thing this section claims from the file.  Nothing else in
section 20 reads it -- sections 20.2 to 20.5 are computed
from `oof_predictions.parquet` and `one_shot_candidate_scores.parquet`, both
unmodified since before this session.

The previously reported "MAX_ENSEMBLE_SD 0.709 vs RANDOM 0.702" therefore
carried no information about tree variance.  Sections 20.3-20.4 replace it with
properly sourced arms; the negative conclusion survives, and gets stronger.

---
""")

    parts.append(f"""
## 20.2 (a) Calibration: the uncertainties are real

{md_table(calib)}

The two ligand-level sources are constant inside a ligand, so no within-ligand
Spearman exists for them; those cells are blank throughout this section.

Within a ligand the signal is weak but real for the two tree-sd variants
({float(within.loc['u_tree_sd', 'within_ligand_rho']):.3f}, CI [{float(within.loc['u_tree_sd', 'ci_low']):.3f}, {float(within.loc['u_tree_sd', 'ci_high']):.3f}] and {float(within.loc['u_tree_sd_mean', 'within_ligand_rho']):.3f}, CI [{float(within.loc['u_tree_sd_mean', 'ci_low']):.3f}, {float(within.loc['u_tree_sd_mean', 'ci_high']):.3f}]);
they are the only intervals that exclude zero, and every other row-level source
is indistinguishable from it.  The `n cells` column is not the same for every
source -- a source that is constant inside a cell yields no Spearman there -- so
that column-to-column comparison is unpaired as printed.  Repeated on the
{int(common.loc['u_tree_sd', 'n_cells_common'])} cells where all seven row-level
sources are defined, the ranking is unchanged: `u_tree_sd`
{float(common.loc['u_tree_sd', 'within_ligand_rho_common_cells']):.3f},
`u_tree_sd_mean` {float(common.loc['u_tree_sd_mean', 'within_ligand_rho_common_cells']):.3f},
`u_model_spread` {float(common.loc['u_model_spread', 'within_ligand_rho_common_cells']):.3f},
`u_cond_nn1` {float(common.loc['u_cond_nn1', 'within_ligand_rho_common_cells']):.3f},
`u_gp_var_design` {float(common.loc['u_gp_var_design', 'within_ligand_rho_common_cells']):.3f}
(`calibration_within_ligand_common.csv`).

*Across* ligands it is strong and unanimous over
seeds: the tree sd ranks which extractant the model will do badly on at rho
{tsd_across:.3f}, the deep-ensemble spread at {float(across.loc['u_model_spread', 'across_ligand_rho_mean']):.3f}, condition-space 1-NN distance
at {float(across.loc['u_cond_nn1', 'across_ligand_rho_mean']):.3f}, mechanistic ligand distance at {float(across.loc['u_lig_mech', 'across_ligand_rho_mean']):.3f}.  Tanimoto distance to the
nearest training ligand is the weakest of them ({float(across.loc['u_lig_tanimoto', 'across_ligand_rho_mean']):.3f}).  `u_gp_var_design` is
*negatively* related to ligand difficulty ({float(across.loc['u_gp_var_design', 'across_ligand_rho_mean']):.3f}), as it should be: it is a
property of the experimental design, not of the chemistry.

Pooled calibration curve for `u_tree_sd`, deciles over all 26,240 held-out
row-seeds:

{md_table(tree_curve)}

Monotone across eight of ten deciles, a factor 2.1 from bottom to top.  By the
usual standard this is a well-calibrated uncertainty.

The same curve computed *within* ligand -- rank the rows inside each ligand-seed
cell, cut into quintiles, subtract that ligand's own mean abs(residual), then
macro-average over the 91 ligands with at least 10 rows -- is an order of
magnitude flatter:

{md_table(wpivot[wcols], float_format='.4f')}

Almost all of the apparent calibration is between-ligand difficulty.  Inside a
ligand, which is the only place a 1-shot acquisition policy ever operates, the
tree sd spans about 0.23 log units from bottom quintile to top, and the
condition-space and GP measures span less.

---

## 20.3 (b) Decision usefulness: does the number rank *candidates*?

Within-ligand Spearman between each source and the exact 1-shot MAE of that
candidate -- positive means high uncertainty picks a *worse* candidate -- macro
over the same 143 ligands with a paired chemotype bootstrap.  The two right-hand
columns are point estimates without intervals; their intervals are in
`decision_spearman.csv`:

{md_table(dec)}

Every model-uncertainty source is flat against candidate quality.  The two
GP-variance sources are the only ones with a clear signal, and it is
**positive**: a high-variance point is a *bad* point to measure.  The last two
columns are the whole story in miniature -- the source that best tracks abs(r)
(`u_tree_sd`, {float(dspear.loc['u_tree_sd', 'rho_vs_abs_resid']):.3f}) is exactly the one that does not track the deviation
from the median ({float(dspear.loc['u_tree_sd', 'rho_vs_median_dev']):.3f}), while the source that does track the deviation
(`u_gp_var_design`, {float(dspear.loc['u_gp_var_design', 'rho_vs_median_dev']):.3f}) does not track abs(r) at all ({float(dspear.loc['u_gp_var_design', 'rho_vs_abs_resid']):.3f}).

### Realised MAE of "measure the extreme candidate"

One ligand one vote, 143 ligands, mean over 5 seeds.  `RANDOM(expected)` is the
exact expectation over candidates, not a sample.  `ORACLE_*` arms read held-out
labels: they are ceilings, not policies.  "extremity of pick" is the mean
abs(percentile of the picked row's residual - 0.5); a uniform random pick sits
at 0.25 by construction.

{md_table(pol)}

Paired chemotype bootstrap against random, positive = the arm beats random:

{md_table(db)}

Read it three ways.

1. **Maximum uncertainty loses, significantly.**  `MAX[u_tree_sd]` {maxtree:.3f} vs
   random {rand:.3f}: {float(b_tree['point']):+.3f} (CI [{float(b_tree['ci95_low']):.3f}, {float(b_tree['ci95_high']):.3f}], {int(b_tree['seeds_positive'])}/5 seeds).
   `MAX[u_model_spread]`, `MAX[u_cond_nn5]` and `MAX[u_gp_var_train]` lose too.
   `MAX[u_gp_var_design]` at {m('MAX[u_gp_var_design]'):.3f} throws away essentially the entire
   value of the measurement -- zero-shot is {zshot:.3f}.
2. **Minimum uncertainty does not rescue it** for the model-based sources:
   `MIN[u_tree_sd]` {m('MIN[u_tree_sd]'):.3f} and `MIN[u_model_spread]` {m('MIN[u_model_spread]'):.3f} are *also*
   worse than random.  Both tails of a model-uncertainty ordering are bad places
   to spend the measurement, which is already the hint that the ordering is on
   the wrong axis entirely.
3. **The one winner is not an uncertainty.**  `MIN[u_gp_var_design]` {gpmin:.3f}
   beats random by {float(b_gp['point']):.3f} (CI [{float(b_gp['ci95_low']):.3f}, {float(b_gp['ci95_high']):.3f}], BCa [{float(b_gp['bca_low']):.3f}, {float(b_gp['bca_high']):.3f}],
   {int(b_gp['units_improved'])}/143 ligands, {int(b_gp['seeds_positive'])}/5 seeds).  That is GP variance used *backwards* --
   the point the rest of the design surrounds most tightly.  It is a
   design-centrality criterion and it lands where `CENTRAL` and `MEDOID` already
   landed ({float(prior.loc['CENTRAL', 'macro_mae']):.3f} and {float(prior.loc['MEDOID', 'macro_mae']):.3f} in the
   pinned snapshot above, 0.646 each in the snapshot section 19 was written from;
   they are not on the same candidate table as the arms in this section and are
   quoted for orientation, not compared).

The ligand-level sources cannot rank rows within a ligand -- they are constant
there -- so their MAX / MIN arms are random tie-breaks and duly score within
noise of random in both directions.  That is a harness consistency check, not a
finding.

---
""")

    parts.append(f"""
## 20.4 (c) The mechanism

Measuring candidate *i* sets the offset to `r_i`, so the resulting error on
every other row *j* is `abs(r_j - r_i)`.  The candidate's score is the mean
absolute deviation of the ligand's residual set *around r_i* -- a convex
function of `r_i`, minimised at the **median** residual.  The policy's job is
not to find the row the model gets right.  It is to find the row whose error is
**typical**.

Within-ligand Spearman, macro over 143 ligands, chemotype CI:

{md_table(mech[['quantity', 'within_ligand_rho', 'ci_low', 'ci_high', 'n_cells']])}

- `abs(r - median r)` ranks candidate quality at rho {float(mech.iloc[0]['within_ligand_rho']):.3f} -- it *is* the
  criterion.  Picking `argmin abs(r_i - median(r))` scores {m('ORACLE_MIN_MEDIAN_DEV'):.4f}, identical
  to the exhaustive 1-shot oracle {orc:.4f} in all {int(ceq['n_cells'])} cells
  (max gap {float(ceq['max_abs_gap_vs_exhaustive_oracle']):.1e}, {int(ceq['n_cells_gap_above_1e_12'])} cells above 1e-12).
- `abs(r)` -- the target of every calibrated uncertainty -- ranks candidate
  quality at only {float(mech.iloc[1]['within_ligand_rho']):.3f}, and ranks the real criterion at {float(mech.iloc[2]['within_ligand_rho']):.3f}.

**So even a perfect uncertainty is a bad policy.**  `ORACLE_MIN_ABS_RESID` --
an oracle that reads the held-out labels and picks the row where the model is
*most accurate* -- scores {minabs:.3f}, which is {-float(b_abs['point']):.3f} log units **worse than
random** (CI [{-float(b_abs['ci95_high']):.3f}, {-float(b_abs['ci95_low']):.3f}], worse on {5 - int(b_abs['seeds_positive'])}/5 seeds).  Perfect
calibration, perfectly deployed, actively hurts.  No improvement in uncertainty
quality fixes that, because the objective is aimed elsewhere.

Why: on an unseen chemotype the error is dominated by a ligand-wide *level*
offset, not by row-to-row noise.

{md_table(lvl_tab)}

A row with small abs(r) is a row where the ligand's large level offset happened
to be cancelled by something local.  Its residual is the *least* representative
of the ligand, so adopting it as the offset transports that cancellation onto
every other row.  Symmetrically, a high-uncertainty row is usually an
extreme-residual row, unrepresentative in the other direction.  Both tails lose;
the middle wins.

The entire leaderboard falls out of one number -- how far from the median
residual the policy's pick lands.  Across the {int(cen['n_arms'])} picking arms, the Spearman
between mean extremity-of-pick and the arm's macro MAE is
**{float(cen['spearman_centrality_vs_macro_mae']):.3f}**.  The oracle arms are *defined* by residual extremity, so
including them makes that partly circular; dropping them leaves
{float(cen['spearman_deployable_only']):.3f} over the {int(cen['n_arms_deployable'])} deployable arms and
{float(cen['spearman_deployable_row_level']):.3f} over the {int(cen['n_arms_deployable_row_level'])} deployable row-level ones,
so it is not.  It is a correlation across arms, not a paired within-ligand
interval, and it is offered as the ordering principle rather than as a test.
The oracle sits at {m('ORACLE_1SHOT', 'macro_centrality'):.3f}, a random pick at 0.25, every
model-uncertainty arm *above* 0.25 in both directions, and the only deployable
arm below it -- `MIN[u_gp_var_design]` at {m('MIN[u_gp_var_design]', 'macro_centrality'):.3f} -- is the only one that beats
random.

Acquisition here is a **centrality** problem, not an **uncertainty** problem,
and uncertainty is a monotone measure of extremity: the wrong sign, on the wrong
axis.

---

## 20.5 Where uncertainty could still have paid: choosing the ligand

The row-level decision is hopeless, but the *ligand*-level one is a different
question.  Given a budget of M measurements over 143 unseen extractants, does
uncertainty pick the right extractants?  Calibration says it should -- the
across-ligand rho against zero-shot error is {tsd_across:.3f}.

It does not, or at least not measurably.  Uncertainty ranks the zero-shot error;
the budget decision needs the *gain* from measuring, which is zero-shot minus
post-correction error:

{md_table(tri_s)}

Macro MAE over all 143 ligands when M of them get one measurement (the
deployable `MIN[u_gp_var_design]` point) and the rest stay zero-shot:

{md_table(tri[tri_cols])}

Paired chemotype bootstrap at M=29, a 20% budget:

{md_table(tb)}

Every source is directionally positive and the best of them agrees on
{int(spread29['seeds_positive'])}/5 seeds, but the chemotype interval covers zero and the
chemotype-weighted macro is {float(spread29['block_macro']):.4f}.  **Not established.**  The gap between
rho {float(triage_s.loc['u_model_spread', 'rho_vs_zero_shot_mae']):.3f} against zero-shot error and rho {float(triage_s.loc['u_model_spread', 'rho_vs_gain_from_one_shot']):.3f} against the gain is the
same phenomenon as 20.4: the one-shot offset removes most of what the
uncertainty was detecting, so knowing where the model is bad barely tells you
where measuring helps.  Oracle triage is worth {float(tri29['RANDOM']) - float(tri29['ORACLE_gain']):.3f} at M=29, so the headroom
is real and unclaimed.

---
""")

    parts.append(f"""
## 20.6 Robustness

- **Cross-model mismatch is not the explanation.**  The tree sd comes from a
  sibling model.  Scoring it against the sibling's *own* residuals instead of
  the frozen model's changes nothing:

{md_table(selfc)}

- **Both tails were tested** for every source (`MAX[...]` and `MIN[...]`), so a
  sign error cannot be hiding a positive result.
- **Ties are broken at random**, not by row order -- the exact failure that made
  the pre-existing `MAX_PREDICTIVE_VARIANCE` arm meaningless.
- **`RANDOM` is exact**: the mean over all candidates, not a 12-repeat sample.
  It lands at {rand:.3f} against the k-shot harness's sampled {float(prior.loc['RANDOM', 'macro_mae']):.3f} in the pinned
  snapshot.  The oracle differs more ({orc:.3f} here vs {float(prior.loc['ORACLE[OFFSET_K1]', 'macro_mae']):.3f} there) because the harness
  picks from a capped random pool and scores on a smaller disjoint evaluation
  subset, which lets its oracle chase evaluation noise.  Every comparison in
  this section is internal to the candidate table, so the offset does not affect
  any claim made here.
- **The independence unit is the chemotype**, not the ligand, in every interval.

---

## 20.7 What to do instead

1. Do not select measurements by model uncertainty.  Both tails lose to random,
   and a *perfect* uncertainty oracle loses to random by {-float(b_abs['point']):.3f}.
2. Select by **design centrality**: `MIN[u_gp_var_design]` ({gpmin:.3f}), and
   `CENTRAL` / `MEDOID` ({float(prior.loc['CENTRAL', 'macro_mae']):.3f} / {float(prior.loc['MEDOID', 'macro_mae']):.3f} in the pinned
   snapshot).  Section 19's stratum rules -- mid-acid, central
   lanthanide, middle of the predicted range -- are the same instruction stated
   in chemistry, and they are the whole of the deployable gain.
3. If uncertainty is to earn a place it must be re-aimed.  The estimand is
   `E abs(r_i - median(r_ligand))`, a deviation-from-own-median predictor, not
   an error-magnitude predictor.  Nothing in the stack estimates it; the best
   correlate found here is a labelless design-geometry quantity
   ({float(dspear.loc['u_gp_var_design', 'rho_vs_median_dev']):.3f}) rather than any model uncertainty ({float(dspear.loc['u_tree_sd', 'rho_vs_median_dev']):.3f} for the tree sd).
4. Uncertainty stays legitimate for **reporting**: it ranks which unseen
   extractants the model will be wrong about (across-ligand rho {tsd_across:.3f}, 5/5
   seeds), which is what an error bar is for.  It describes the model's state.
   It is not a plan for the next experiment.

---

## Files

| file | contents |
|---|---|
| `row_uncertainty.parquet` | 26,240 held-out row-seeds, residual + 9 uncertainty columns |
| `candidate_uncertainty.parquet` | the 1-shot candidate table joined to those columns |
| `calibration_within_ligand.csv`, `calibration_across_ligand.csv` | (a) Spearman, both units |
| `calibration_curve_pooled.csv`, `calibration_curve_within_ligand.csv` | (a) binned calibration curves |
| `calibration_self_consistency.csv` | sibling sd vs the sibling's own error |
| `decision_spearman.csv`, `decision_rho_detail.parquet` | (b) per-ligand Spearman vs candidate quality |
| `decision_policies.csv`, `policy_detail.parquet` | (b) realised MAE of every MAX / MIN / oracle arm |
| `decision_bootstrap_vs_random.csv` | (b) paired chemotype bootstrap |
| `mechanism_spearman.csv`, `mechanism_detail.parquet`, `level_vs_shape.csv` | (c) the deviation-from-median explanation |
| `centrality_explains_leaderboard.csv` | (c) the one number that orders the leaderboard, with and without the oracle arms |
| `mechanism_oracle_equivalence.csv` | (c) argmin abs(r - median r) against the exhaustive oracle, cell by cell |
| `calibration_within_ligand_common.csv` | (a) the same within-ligand rho on the cells where every source is defined |
| `triage_spearman.csv`, `triage_budget_curve.csv`, `triage_bootstrap.csv`, `triage_ligand_table.csv` | the ligand-level budget question |
| `audit_prior_policies.csv`, `audit_prior_macro.csv`, `audit_prediction_sd_availability.csv` | the degenerate pre-existing arms |
| `gp_axes_used.csv` | which 1-3 condition axes each ligand's GP used |

Built by `scripts/gen8_uncertainty.py` (sources),
`scripts/gen8_uncertainty_analysis.py` (scoring),
`scripts/gen8_uncertainty_report.py` (this file).
""")

    (OUT / "uncertainty.md").write_text("\n".join(parts))
    print("wrote", OUT / "uncertainty.md")


if __name__ == "__main__":
    main()
